Repository orbis-education/shared-components, pull requests merged in 2025-03, with the labels that each got.

#63 Separates css build file
  package-lock.json
  package.json
  vite.config.js
Labels: bug, enhancement

#67 add new icons and update some comments
  lib/css/utilities/Variables.css
  lib/css/vendor/FontAwesome.css
  package-lock.json
  package.json
Labels: enhancement

#69 updating package version to 1.2.0
  package-lock.json
  package.json
Labels: bug

#71 rename css files to lowercase
  lib/css/components/alertPopup.css
  lib/css/components/buttons.css
  lib/css/components/form.css
  lib/css/components/modal.css
  lib/css/components/spinner.css
  lib/css/components/tabs.css
  lib/css/components/tooltip.css
  lib/css/index.css
  lib/css/layout/base.css
  lib/css/layout/header.css
  lib/css/layout/rows.css
  lib/css/layout/sectionBlock.css
  lib/css/layout/table.css
  lib/css/utilities/utilities.css
  lib/css/utilities/variables.css
  lib/css/vendor/fontAwesome.css
  package-lock.json
  package.json
Labels: enhancement
